apiVersion: apps/v1
kind: Deployment
metadata:
  name: zy-tools
  annotations:
    kubesphere.io/description: 资源配额导出
spec:
  selector:
    matchLabels:
      app: zy-tools
  template:
    metadata:
      labels:
        app: zy-tools
    spec:
      containers:
        - name: zy-tools
          image: sit-registry.qm.cn/sit-fc2-qm-monitoring-kube-service/zy-tools:0.4
          env:
            - name: GIN_MODE
              value: release
            - name: GO_ENV
              value: prod
            - name: KUBESPHERE_APISERVER
              value: "http://ks-apiserver.kubesphere-system.svc"
            - name: KUBESPHERE_USERNAME
              value: "admin"
            - name: KUBESPHERE_PASSWORD
              value: "Xiang1234"
            - name: KUBESPHERE_DEFAULTPASSWORD
              value: "Xiang1234"
            - name: META_ENV
              value: "prod"
            - name: META_APPKEY
              value: "1529bc5396bf441ea6f0fabe35b2f0e3"
            - name: META_APPSECRET
              value: "72f2cfe134904a04a5385453a897cfe1"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 60
            timeoutSeconds: 30
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 512Mi
          imagePullPolicy: IfNotPresent